"""empty message

Revision ID: 79c00bf5f57c
Revises: 
Create Date: 2023-06-03 23:30:33.703294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79c00bf5f57c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'manager',
               existing_type=mysql.VARCHAR(length=100),
               comment='管理者',
               existing_nullable=False)
    op.alter_column('equipment', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='装备名',
               existing_nullable=False)
    op.alter_column('equipment', 'academy',
               existing_type=mysql.VARCHAR(length=100),
               comment='所属学院',
               existing_nullable=False)
    op.alter_column('equipment', 'place',
               existing_type=mysql.VARCHAR(length=100),
               comment='存放地点',
               existing_nullable=False)
    op.alter_column('equipment', 'usage',
               existing_type=mysql.VARCHAR(length=100),
               comment='使用方法',
               existing_nullable=False)
    op.alter_column('feedback', 'title',
               existing_type=mysql.VARCHAR(length=100),
               comment='反馈标题',
               existing_nullable=False)
    op.alter_column('feedback', 'content',
               existing_type=mysql.VARCHAR(length=100),
               comment='反馈内容',
               existing_nullable=False)
    op.drop_column('feedback', 'identification')
    op.drop_column('feedback', 'name')
    op.alter_column('lab', 'manager',
               existing_type=mysql.VARCHAR(length=100),
               comment='管理者',
               existing_nullable=False)
    op.alter_column('lab', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='实验室名字',
               existing_nullable=False)
    op.alter_column('lab', 'academy',
               existing_type=mysql.VARCHAR(length=100),
               comment='学院',
               existing_nullable=False)
    op.alter_column('lab', 'place',
               existing_type=mysql.VARCHAR(length=100),
               comment='实验室地点',
               existing_nullable=False)
    op.drop_column('lab', 'usage')
    op.alter_column('orders', 'startTime',
               existing_type=mysql.VARCHAR(length=100),
               comment='开始时间',
               existing_nullable=False)
    op.alter_column('orders', 'untilTime',
               existing_type=mysql.VARCHAR(length=100),
               comment='结束时间',
               existing_nullable=False)
    op.alter_column('orders', 'orderStatus',
               existing_type=mysql.VARCHAR(length=100),
               comment='状态',
               existing_nullable=False)
    op.alter_column('orders', 'ifChecked',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               comment='是否核对')
    op.create_unique_constraint(None, 'orders', ['id'])
    op.drop_column('orders', 'applicantName')
    op.drop_column('orders', 'managerName')
    op.drop_column('orders', 'itemPlace')
    op.drop_column('orders', 'itemName')
    op.drop_column('orders', 'applicantIDNumber')
    op.drop_column('orders', 'itemID')
    op.drop_column('orders', 'reserveReason')
    op.add_column('user', sa.Column('user_name', sa.String(length=100), nullable=False, comment='用户名'))
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               comment='密码',
               existing_nullable=False)
    op.alter_column('user', 'number',
               existing_type=mysql.VARCHAR(length=100),
               comment='学号',
               existing_nullable=False)
    op.alter_column('user', 'identification',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               comment='身份')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.alter_column('user', 'identification',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment='身份')
    op.alter_column('user', 'number',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='学号',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user', 'user_name')
    op.add_column('orders', sa.Column('reserveReason', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('itemID', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('applicantIDNumber', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('itemName', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('itemPlace', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('managerName', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('applicantName', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'ifChecked',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment='是否核对')
    op.alter_column('orders', 'orderStatus',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('orders', 'untilTime',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=False)
    op.alter_column('orders', 'startTime',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=False)
    op.add_column('lab', sa.Column('usage', mysql.VARCHAR(length=100), nullable=False))
    op.alter_column('lab', 'place',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='实验室地点',
               existing_nullable=False)
    op.alter_column('lab', 'academy',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='学院',
               existing_nullable=False)
    op.alter_column('lab', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='实验室名字',
               existing_nullable=False)
    op.alter_column('lab', 'manager',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='管理者',
               existing_nullable=False)
    op.add_column('feedback', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('feedback', sa.Column('identification', mysql.VARCHAR(length=100), nullable=False))
    op.alter_column('feedback', 'content',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='反馈内容',
               existing_nullable=False)
    op.alter_column('feedback', 'title',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='反馈标题',
               existing_nullable=False)
    op.alter_column('equipment', 'usage',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='使用方法',
               existing_nullable=False)
    op.alter_column('equipment', 'place',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='存放地点',
               existing_nullable=False)
    op.alter_column('equipment', 'academy',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='所属学院',
               existing_nullable=False)
    op.alter_column('equipment', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='装备名',
               existing_nullable=False)
    op.alter_column('equipment', 'manager',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='管理者',
               existing_nullable=False)
    # ### end Alembic commands ###
